name: Laravel Pint

on:
  pull_request:

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Change to a stable version if 8.3 is not available
          tools: composer:v2

      - name: Install Pint
        run: composer require laravel/pint --dev

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      - name: Placeholder Step
        run: echo "TODO"
