name: Laravel Pint

on:
  pull_request:
  push:


jobs:
  laravel-pint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install php and composer 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          # extensions: mbstring, bcmath, sqlite
          tools: composer:v1



      - name: Install Pint
        run: composer require laravel/pint --dev

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      - name: Push Changes Back to Repository
        run: echo "TODO"
      
