name: Laravel Test

on:
  pull_request:
  push:



jobs:
  run-laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        

      - name: install php and composer 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          # extensions: mbstring, bcmath, sqlite
          tools: composer:v2



      - name: Install Dependencies
        run: composer install -q -n

      - name: Prep Environment
        run: |
          cp .env.example .env
          php artisan key:generate
      
      - name: Run Tests
        run: php artisan test  --compact --colors=always
 
